name: CI
on: [push]
jobs:
  validate:
    name: Validate cluster
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Kops
        uses: yehiyam/kops-action@latest
        with:
          command: validate cluster
          cluster-name: ${{ secrets.CICD_CLUSTER_NAME }}
          state-store: ${{ secrets.CICD_STATE_STORE }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
